# environment
env = "pro"

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "INFO"

[app]
name = "blog-test"
address = "127.0.0.1:1323"


[db]
db_name = "blog"
user_name = "root"
pwd  = "37986712"
host = "localhost"


[jwt]
sign_method = "HS256"
secret = "dfjalsdjflasd"
exp = 72  # 单位: hours